// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwvbZxigLoFWSjtbemYHo65c4aTDn56IE',
    appId: '1:188938523542:web:de3a9ff2bd5c06a56343b7',
    messagingSenderId: '188938523542',
    projectId: 'sellertaybgo',
    authDomain: 'sellertaybgo.firebaseapp.com',
    storageBucket: 'sellertaybgo.firebasestorage.app',
    measurementId: 'G-1N9GP0MHYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0krx5c-Sh4QYYl7GHCTqAc2nDEAp4qNE',
    appId: '1:188938523542:android:bd82c7143bf50ca46343b7',
    messagingSenderId: '188938523542',
    projectId: 'sellertaybgo',
    storageBucket: 'sellertaybgo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-hytdKnDrSplmnjAL_AOUAP9YhtIi8Zs',
    appId: '1:861868751268:ios:72e72cf8cc316904352931',
    messagingSenderId: '861868751268',
    projectId: 'tybetogoseller',
    storageBucket: 'tybetogoseller.firebasestorage.app',
    iosBundleId: 'com.tybetogo.seller',
  );
}
