// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftvY9C016g1qAFyK8Ml3_OSvm-ZGUW74',
    appId: '1:861868751268:web:79f3ff23d9712bc0352931',
    messagingSenderId: '861868751268',
    projectId: 'tybetogoseller',
    authDomain: 'tybetogoseller.firebaseapp.com',
    storageBucket: 'tybetogoseller.firebasestorage.app',
    measurementId: 'G-VDPLRZ1852',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJ0ZMTIFUO2ZGNIAP-p4yzkF5fNNoBuM',
    appId: '1:861868751268:android:6e861d2c9ec2db5a352931',
    messagingSenderId: '861868751268',
    projectId: 'tybetogoseller',
    storageBucket: 'tybetogoseller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-hytdKnDrSplmnjAL_AOUAP9YhtIi8Zs',
    appId: '1:861868751268:ios:72e72cf8cc316904352931',
    messagingSenderId: '861868751268',
    projectId: 'tybetogoseller',
    storageBucket: 'tybetogoseller.firebasestorage.app',
    iosBundleId: 'com.tybetogo.seller',
  );
}
